#!/usr/bin/env bash

# ThePrimeagen Original script

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/code ~/code/ameh/ ~/code/vdb/ -mindepth 1 -maxdepth 1 -type d | fzf-tmux -p)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [ -n "$TMUX" ]; then
  tmux detach-client -E "tmux new-session -A -s $selected_name -c $selected"
fi

tmux new-session -A -s "$selected_name" -c "$selected"

exit 0
